### ISSUE TITLE
Rich-Presence doesn't work 

### ISSUE THREAD

**Issue by Syhix** [xQynx/Rich-Presence#5]
when I run the node index.js command I have an error

```Starting up ..
   Gathering Login ..
      Logged in!
   Client ..
      Ready
   Presence ..
      *  Loaded [/presence]
      *  Loaded [/assets]
      *  Loaded [/interaction]
      Presence Ready





(node:9364) UnhandledPromiseRejectionWarning: Error: child "activity" fails because [child "assets" fails because ["smal_text" is not allowed]]
    at RPCClient._onRpcMessage (C:\Users\cococ\Desktop\Rich-Presence-master\node_modules\discord-rpc\src\client.js:185:19)
    at IPCTransport.emit (events.js:311:20)
    at C:\Users\cococ\Desktop\Rich-Presence-master\node_modules\discord-rpc\src\transports\ipc.js:134:18
    at decode (C:\Users\cococ\Desktop\Rich-Presence-master\node_modules\discord-rpc\src\transports\ipc.js:92:5)
    at Socket.<anonymous> (C:\Users\cococ\Desktop\Rich-Presence-master\node_modules\discord-rpc\src\transports\ipc.js:120:7)
    at Socket.emit (events.js:311:20)
    at emitReadable_ (_stream_readable.js:562:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
(node:9364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9364) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by qvnx** [comment]
Yup! That's known. That's due to me **accidentally merging a branch into main**. Currently it's all messy and broken and I need to find time to work on it. I'll hopefully get a chance in a couple days or so. Thanks!

**Comment by Syhix** [comment]
> Ouaip! C'est connu. Cela est dû au fait que j'ai **accidentellement fusionné une branche dans main** . Actuellement, tout est en désordre et cassé et j'ai besoin de trouver du temps pour y travailler. J'espère avoir une chance dans quelques jours environ. Merci!

Okay, good luck :)
